modLoader="javafml"
loaderVersion="[47,)"
license="MIT"

[[mods]]
modId="waystoneinjector"
version="1.0.0"
displayName="Waystone Button Injector"
description="Injects configurable buttons into the Waystones GUI and sends a server packet to run commands."
authors=["RunawayStone"]

[[dependencies.waystoneinjector]]
    modId="forge"
    mandatory=true
    versionRange="[47,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.waystoneinjector]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="NONE"
    side="BOTH"
